---
- hosts: localhost
  gather_facts: false
  
  vars:
    content:
      key1: value1
      key2: value2
  
  pre_tasks:
  - name: Checkout roles
    command: ansible-galaxy install -r requirements.yaml
  tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration

  - name: Test file 
    local_action: copy content={{ content | to_yaml }} dest={{ output_dir }}/output.yaml
