---
- src: https://github.com/ekara-platform/ansible-role-configuration.git
  version: v1.0.0
  name: ekara.configuration

- src: https://github.com/ekara-platform/ansible-role-filesystem.git
  version: master
  name: ekara.filesystem
